#!/usr/bin/sh
if [ "${BAT_MANPAGER:-true}" = true ] && [ -f /bin/bat ]; then
  export MANPAGER="sh -c 'awk '\''{ gsub(/\x1B\[[0-9;]*m/, \"\", \$0); gsub(/.\x08/, \"\", \$0); print }'\'' | bat -p -lman'"
fi
