#!/usr/bin/sh
if [ "${ENABLE_FZF:-true}" = "true" ] && [ -f "/bin/fzf" ]; then
  export FZF_DEFAULT_OPTS="
        --color=fg:#908caa,hl:#ebbcba
        --color=fg+:#e0def4,hl+:#ebbcba
        --color=border:#403d52,header:#31748f,gutter:#191724
        --color=pointer:#c4a7e7,marker:#ebbc92,prompt:#908caa
        "
  source <(fzf --zsh)
fi 
