#!/usr/bin/bash

if [[ "${ENABLE_KITTY:-true}" == true && $TERM == *kitty* ]]; then
  if [[ -n "$KITTY_INSTALLATION_DIR" ]]; then
    export KITTY_SHELL_INTEGRATION="enabled"
    autoload -Uz -- "$KITTY_INSTALLATION_DIR"/shell-integration/zsh/kitty-integration
    kitty-integration
    unfunction kitty-integration
  fi
  alias icat="kitten icat"
  alias mpvcat="mpv -vo kitty"
  alias kssh="kitten ssh"
fi
