#!/usr/bin/env bash
DOTS_DIR=${0:A:h}
[[ "$RC_DEBUG_MODE" == true ]] && echo "found dots dir $DOTS_DIR"
RC_DIR="$DOTS_DIR/rc.d"
[[ "$RC_DEBUG_MODE" == true ]] && echo "rc dir: $RC_DIR"

if [ "$SHELL" = "/usr/bin/zsh" ] || [ "$SHELL" = "/bin/zsh" ]; then
  [[ "$RC_DEBUG_MODE" == true ]] && echo "zsh detected as shell"
  . "$DOTS_DIR/zsh/zshrc"
fi

alias pubip='curl http://ifconfig.me'
alias timestamp='date -u +'%Y%m%dT%H%M%SZ''
alias datestamp='date -u +'%Y%m%d''
alias tclock="tty-clock -c -C 5"
alias fetch='clear && fastfetch'
alias neofetch="fastfetch"
alias s='sudo'
alias se='sudoedit'
alias ll='ls -l'
alias la='ls -A'
alias l='ls -CF'
alias synthwave="mpv --no-video 'https://www.youtube.com/watch?v=4xDzrJKXOOY'"
alias lofi="mpv --no-video 'https://www.youtube.com/watch?v=jfKfPfyJRdk'"
alias sys='systemctl'
alias usys='systemctl --user'
alias sdr="systemctl daemon-reload"
alias sr="systemctl restart"
alias jeu="journalctl -eu"
alias je="journalctl -e"
alias jfu="journalctl -fu"
alias jf="journalctl -f"
if [ -v "podman" ]; then alias podman-unit-generate-test="/usr/lib/systemd/system-generators/podman-system-generator --dryrun"; fi
if [ -v "swww" ]; then alias swww-cur-img="swww query | head -n 1 | cut -d ',' -f 3 | cut -d ' ' -f 5"; fi
if [ -v "rsync" ]; then alias rsync='rsync --info=progress2'; fi

for file in $RC_DIR/*; do
  if [ -f "$file" ]; then
    [[ "$RC_DEBUG_MODE" == true ]] && echo "sourcing: $file"
    source $file
  fi
done

unset has_command
