#!/usr/bin/env bash

iDIR="$HOME/.config/mako/icons"

# Get brightness
get_backlight() {
  max=15360
  LIGHT=$(brightnessctl -m | cut -d "," -f 4 | sed "s/%//")

	echo "${LIGHT}"
}

# Get icons
get_icon() {
	current="$(get_backlight)"
	if [[ ("$current" -ge "0") && ("$current" -le "12") ]]; then
		icon="$iDIR/brightness-20.png"
	elif [[ ("$current" -ge "12") && ("$current" -le "25") ]]; then
		icon="$iDIR/brightness-40.png"
	elif [[ ("$current" -ge "25") && ("$current" -le "50") ]]; then
		icon="$iDIR/brightness-60.png"
	elif [[ ("$current" -ge "50") && ("$current" -le "75") ]]; then
		icon="$iDIR/brightness-80.png"
	elif [[ ("$current" -ge "75") && ("$current" -le "100") ]]; then
		icon="$iDIR/brightness-100.png"
	fi
}

# Notify
notify_user() {
	notify-send --app-name=volume -h int:value:$(get_backlight) -h string:x-canonical-private-synchronous:sys-notify -u low -i "$icon" "$(get_backlight)%"
}

# Increase brightness
inc_backlight() {
	brightnessctl s +5% && get_icon && notify_user
}

# Decrease brightness
dec_backlight() {
	brightnessctl s 5%- && get_icon && notify_user
}

# Execute accordingly
if [[ "$1" == "--get" ]]; then
	get_backlight
elif [[ "$1" == "--inc" ]]; then
	inc_backlight
elif [[ "$1" == "--dec" ]]; then
	dec_backlight
else
	get_backlight
fi
