decoration {
  rounding = 8
  rounding_power = 2
  active_opacity = 1
  inactive_opacity = 0.95
  dim_inactive = true
  dim_strength = 0.1
  dim_special = 0.5
  blur {
    enabled = true
    xray = true
    size = 3
    brightness = 0.7
    passes = 2
    vibrancy = 0.2
    vibrancy_darkness = 0.2
    noise = 0.05
    popups = false
  }
  shadow {
    enabled = true
    ignore_window = true
    range = 20
    offset = 0 2
    render_power = 10
    color = rgba(00000020)
  }
  dim_inactive = true
  dim_strength = 0.05
  dim_special = 0.2
}
