source=~/.config/hypr/binds.conf
env = HYPRCURSOR_THEME,rose-pine-hyprcursor
env = HYPRCURSOR_SIZE,24
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland
env = QT_QPA_PLATFORMTHEME,gnome
exec-once = waybar
exec-once = mako
exec-once = hypridle
exec-once = awww-daemon
exec-once = systemctl --user start hyprpolkitagent
exec-once = wl-paste --type text --watch cliphist store #Stores only text data
exec-once = wl-paste --type image --watch cliphist store #Stores only image data
monitor=,preferred,auto,1
monitor=DP-7,preferred,auto-right,1
monitor=DP-4,preferred,auto-left,1
monitor=DP-3,1920x1080,auto-right,1
monitor=eDP-1,preferred,auto-down,1

input {
    kb_layout = us
    follow_mouse = 1
    touchpad {
        natural_scroll = yes
    }
    sensitivity = 0.3 # -1.0 - 1.0, 0 means no modification.
    # kb_options = caps:swapescape
}

general {
    gaps_in = 4
    gaps_out = 9
    border_size = 0
    layout = dwindle
    gaps_workspaces = 50
}

scrolling {
  column_width = 0.4
}

dwindle {
    preserve_split = true
    smart_split = false
    smart_resizing = false
    # precise_mouse_move = true
}

gestures {
  #workspace_swipe = on
}

misc {
    force_default_wallpaper = -1
    enable_swallow = false
    swallow_regex = ^(kitty)$
}

decoration {
  rounding = 8
  rounding_power = 2
  active_opacity = 1
  # inactive_opacity = 0.95
  dim_inactive = true
  dim_strength = 0.1
  dim_special = 0.5
  blur {
    enabled = true
    xray = true
    size = 2
    brightness = 0.7
    passes = 1
    vibrancy = 0.2
    vibrancy_darkness = 0.2
    noise = 0.05
    popups = false
  }
  shadow {
    enabled = false
    ignore_window = true
    range = 20
    offset = 0 2
    render_power = 10
    color = rgba(00000020)
  }
  dim_inactive = true
  dim_strength = 0.05
  dim_special = 0.2
}


animations {
    enabled = true
    # Curves
    bezier = expressiveFastSpatial, 0.42, 1.67, 0.21, 0.90
    bezier = expressiveSlowSpatial, 0.39, 1.29, 0.35, 0.98
    bezier = expressiveDefaultSpatial, 0.38, 1.21, 0.22, 1.00
    bezier = emphasizedDecel, 0.05, 0.7, 0.1, 1
    bezier = emphasizedAccel, 0.3, 0, 0.8, 0.15
    bezier = standardDecel, 0, 0, 0, 1
    bezier = menu_decel, 0.1, 1, 0, 1
    bezier = menu_accel, 0.52, 0.03, 0.72, 0.08
    bezier = stall, 1, -0.1, 0.7, 0.85
    # Configs
    # windows
    animation = windowsIn, 1, 3, emphasizedDecel, popin 80%
    animation = fadeIn, 1, 3, emphasizedDecel
    animation = windowsOut, 1, 2, emphasizedDecel, popin 90%
    animation = fadeOut, 1, 2, emphasizedDecel
    animation = windowsMove, 1, 3, emphasizedDecel, slide
    animation = border, 1, 10, emphasizedDecel
    # layers
    animation = layersIn, 1, 2.7, emphasizedDecel, popin 93%
    animation = layersOut, 1, 2.4, menu_accel, popin 94%
    # fade
    animation = fadeLayersIn, 1, 0.5, menu_decel
    animation = fadeLayersOut, 1, 2.7, stall
    # workspaces
    animation = workspaces, 1, 7, menu_decel, slide
    ## specialWorkspace
    animation = specialWorkspaceIn, 1, 2.8, emphasizedDecel, slidevert
    animation = specialWorkspaceOut, 1, 1.2, emphasizedAccel, slidevert
    # zoom
    animation = zoomFactor, 1, 3, standardDecel
}
