source=~/.config/hypr/themes/mocha.conf

background=$base
base=$surface
alternate_base=$overlay
text=$text
bright_text=$text
accent=$lavendar
accent_secondary=$love
font_family=JetBrains Mono Nerd Font Mono
font_family_monospace=JetBrains Mono Nerd Font Mono
#h1_size
#h2_size
#h3_size
#font_size
#small_font_size
