source=~/.config/hypr/themes/mocha.conf

background=$base
base=$surface0
alternate_base=$overlay0
text=$text
bright_text=$text
accent=$lavender
accent_secondary=$mauve
font_family=JetBrains Mono Nerd Font Mono
font_family_monospace=JetBrains Mono Nerd Font Mono
#h1_size
#h2_size
#h3_size
#font_size
#small_font_size
